# Generated by Django 4.2.6 on 2023-10-15 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50, unique=True)),
                ('elo_rating', models.IntegerField(default=400)),
                ('opponent_average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('number_of_games_played', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['player_name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(verbose_name='date')),
                ('rating', models.IntegerField(verbose_name='elo rating')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elo.player')),
            ],
            options={
                'ordering': ['player', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_score', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('team_2_score', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('date_played', models.DateField(verbose_name='date played')),
                ('updates_performed', models.BooleanField(default=False, verbose_name='player ratings updated?')),
                ('team_1_attack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_1_attack', to='elo.player')),
                ('team_1_defense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_1_defense', to='elo.player')),
                ('team_2_attack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_2_attack', to='elo.player')),
                ('team_2_defense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_2_defense', to='elo.player')),
            ],
            options={
                'ordering': ['-date_played'],
            },
        ),
    ]
