# Generated by Django 4.2.5 on 2023-10-04 18:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=50, unique=True)),
                ("elo_rating", models.IntegerField(default=400)),
                (
                    "opponent_average_rating",
                    models.DecimalField(decimal_places=2, default=None, max_digits=10),
                ),
                ("number_of_games_played", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "winner",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ]
                    ),
                ),
                (
                    "team_1_attack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_1_attack",
                        to="elo.player",
                    ),
                ),
                (
                    "team_1_defense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_1_defense",
                        to="elo.player",
                    ),
                ),
                (
                    "team_2_attack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_2_attack",
                        to="elo.player",
                    ),
                ),
                (
                    "team_2_defense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_2_defense",
                        to="elo.player",
                    ),
                ),
            ],
        ),
    ]
