# Generated by Django 4.2.5 on 2023-10-04 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("elo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="date_played",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="date played"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="player",
            name="opponent_average_rating",
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
    ]
