# Generated by Django 4.2.5 on 2023-10-04 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elo", "0002_game_date_played_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="winner",
        ),
        migrations.AddField(
            model_name="game",
            name="team_1_score",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="team_2_score",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
            preserve_default=False,
        ),
    ]
