# Generated by Django 4.2.6 on 2023-10-21 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elo', '0002_alter_playerrating_options_remove_player_elo_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': [django.db.models.functions.text.Upper('player_name')]},
        ),
        migrations.AlterModelOptions(
            name='playerrating',
            options={'ordering': ['player_id', 'timestamp']},
        ),
        migrations.AddField(
            model_name='game',
            name='submitted_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
