# Generated by Django 4.2.5 on 2023-10-04 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elo", "0003_remove_game_winner_game_team_1_score_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-date_played"]},
        ),
    ]
