# Generated by Django 4.2.5 on 2023-10-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elo", "0004_alter_game_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="opponent_average_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
