# Generated by Django 4.2.5 on 2023-10-10 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elo", "0005_alter_player_opponent_average_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["player_name"]},
        ),
        migrations.CreateModel(
            name="PlayerRatings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateField(verbose_name="date")),
                ("rating", models.IntegerField(verbose_name="elo rating")),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="elo.player"
                    ),
                ),
            ],
        ),
    ]
