# Generated by Django 4.2.5 on 2023-10-10 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elo", "0006_alter_player_options_playerratings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlayerRatings",
            new_name="PlayerRating",
        ),
    ]
