# Generated by Django 4.2.5 on 2023-10-10 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elo", "0007_rename_playerratings_playerrating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playerrating",
            options={"ordering": ["player", "-timestamp"]},
        ),
        migrations.RemoveField(
            model_name="player",
            name="elo_rating",
        ),
    ]
