# Generated by Django 4.2.5 on 2023-10-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elo", "0008_alter_playerrating_options_remove_player_elo_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="elo_rating",
            field=models.IntegerField(default=400),
        ),
    ]
